sculpin:
    output_dir: public_%kernel.environment%
    exclude:
        - _sass/**
sculpin_content_types:
    projects:
        type: path
        enabled: true
        permalink: :filename
        taxonomies:
            - tags
            - categories
    posts:
        enabled: false
